baseURL = "https://tryoasnafi.my.id/"
languageCode = "id-ID"
defaultContentLanguage = "id"
title = "Tulisan harian asnafi"

theme = "garlic"

googleAnalytics = ""
disqusShortname = ""

enableEmoji = true

footnotereturnlinkcontents = "↩"

[author]
    name = "Tryo Asnafi"
    homepage = "https://twitter.com/ardiantapargo"
    bio = "Suka main sama kucing dan pinguin, kurang suka sama jendela."
    image = "https://themes.gohugo.io/theme/liva-hugo/images/author.jpg"
    
[social]
    facebook = "https://www.facebook.com/tryoasnafi"
    github = "https://github.com/tryoasnafi"
    email = "tryoasnafi@gmail.com"

[permalinks]
    artikel = "/:slug/"

[taxonomies]
    tag = "topik"
    category = "kategori"
    series = "seri"